# -*- coding: utf-8 -*-
"""final

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gKAWU0RR8iVl-DajSaPK8VTyeV5lTw1M
"""

from cucim import CuImage
import gdal
import cupy
image_g = gdal.open()
raster_g = image_g.ReadAsArray()
image_c = cp.array(raster_g)
overview_levels = 4
pyramid = cucim.skimage.transform.pyramid_gaussian(input, max_layer = 4)
layers = []
for i, layers in enumerate(pyramid):
  layer.append(layers)
final = layer[1].get()

driver = gdal.GetDriverByName('GTiff')
overview_ds = driver.Create(output_raster, final.RasterXSize, final.RasterYSize, final.RasterCount, final.GetRasterBand(1).DataType)
overview_ds.SetProjection(image_g.GetProjection())
overview_ds.SetGeoTransform(image_g.GetGeoTransform())

for level in overview_levels:
  overview_width = image_g.RasterXSize
  overview_height = image_g.RasterYSize
  overview_ds.GetRasterBand(level).WriteArray(final[:,:, level])

#buffer = image_g.ReadRaster(0, 0, ds.RasterXSize, ds.RasterYSize, buf_xsize=overview_width, buf_ysize=overview_height)